# https://travis-ci.org/zuoxingdong/lagom
sudo: false

language: python
# Set Python version
python:
    - '3.6'

# Install dependencies
install:
    # Build virtual environment and install PyTorch
    - sudo apt update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda create -q -n test-environment -c pytorch python=$TRAVIS_PYTHON_VERSION numpy mock pytorch-cpu
    - source activate test-environment
    - python setup.py install
    # Install required dependencies
    - pip install -r requirements.txt
# Command to run tests
script:
    - pip install -e .
    - pytest test/ -v  # run test files
    - flake8  # check code style and quality
    
# Only master branch
branches:
    only:
        - master
